src/TextAnalyzerWeb/Controllers/DocumentsController.cs
using Data.Models;
using Data.Storage;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TextAnalyzerWeb.Controllers
{
    public class DocumentsController : Controller
    {
        // GET: Documents
        [HttpGet]
        public ActionResult Index()
        {
            List<Document> documents;
            using (var ctx = new TextAnalyzerDb())
                documents = ctx.Documents.ToList();
            return View(documents);
        }

        // GET: Documents/Details/5
        public ActionResult Details(int id)
        {
            Document doc;
            using (var ctx = new TextAnalyzerDb())
                doc = ctx.Documents.FirstOrDefault(x => x.Id == id);
            return View(doc);
        }

        // GET: Documents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Documents/Create
        [HttpPost]
        public ActionResult Upload()
        {
            try
            {
                var stream = Request.Files[0].InputStream;
                string header;
                DocContents contents;
                using (var sr = new StreamReader(stream))
                {
                    header = sr.ReadLine();
                    if (header.Length > Document.MaxHeaderLength)
                        header = header.Substring(0, Document.MaxHeaderLength);
                }
                stream.Position = 0;
                using (var br = new BinaryReader(stream))
                    contents = new DocContents() { Contents = br.ReadBytes((int)stream.Length) };
                using (var ctx = new TextAnalyzerDb())
                {
                    ctx.Documents.Add(new Document() { Header = header, Contents = contents });
                    ctx.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Documents/Delete/5
        public ActionResult Delete(int id)
        {
            Document doc;
            using (var ctx = new TextAnalyzerDb())
                doc = ctx.Documents.Find(id);
            return View(doc);
        }

        // POST: Documents/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (var ctx = new TextAnalyzerDb())
                {
                    var doc = ctx.Documents.FirstOrDefault(x => x.Id == id);
                    if (doc != null)
                    {
                        doc.Contents.Contents = null;
                        ctx.Documents.Remove(doc);
                        ctx.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }   
            catch
            {
                return View();
            }
        }
    }
}

src/TextAnalyzerWeb/Views/Documents/Create.cshtml
@model Data.Models.Document

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создать</h2>


@using (Html.BeginForm("Upload", "Documents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="FileUpload" />
    <input type="submit" name="file" id="Submit" value="Загрузить" />
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/TextAnalyzerWeb/Views/Documents/Delete.cshtml
@model Data.Models.Document

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удалить</h2>

<h3>Подтверждаете удаление?</h3>
<div>
    <h4>Документ</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>

        <dd>
           @Html.DisplayFor(model => model.Header)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

src/TextAnalyzerWeb/Views/Documents/Index.cshtml
@model IEnumerable<Data.Models.Document>

@{
    ViewBag.Title = "DocumentsListView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Documents</h2>

<p>
    @Html.ActionLink("Создать новый", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Header)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPhantom)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Header)
        </td>
        <td>
            @item.IsPhantom.ToString()
        </td>
        <td>
            @Html.ActionLink("Удалить", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>